name: webconnector-lite 
base: core20 
version: '1.0.3' 
summary: WebConnector lite server  
description: |
  Simple WebSocket server; accesses ctrlX Data Layer via REST API

grade: stable
confinement: strict 

architectures:
  - build-on: arm64

parts:
  webconnector-lite:
    plugin: python
    source: .
    python-packages:
      - asyncio
      - websockets
      - requests
      - aiohttp
      - async_timeout

apps:
  webconnector-lite:
    command: bin/webconnector-lite
    plugs:
      - network
      - network-control
      - network-bind
      - home
    daemon: simple
    restart-condition: always
